version: '3.8'  # Use a more recent compose file version

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - "5001:80"  # Host:Container

  flask-app:
    build: ./website
    volumes:
      - ./website:/usr/src/app
    ports:
      - "5000:80"  # Host:Container
    depends_on:
      - laptop-service  # Ensure laptop-service is running first
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80

networks:
  default:
    driver: bridge  # Define a bridge network for container communication
